[workspace]
resolver = "3"
members = [
    "core",
    "core/fuzz"
]

[workspace.package]
version = "0.1.0"
authors = ["Jay Tauron <jay@jaytauron.xyz>"]
license = "MIT"
repository = "https://github.com/0jdxt/magnetronic"
description = "torrent client"
